name: MoBoxHunter
version: '${project.version}'
api-version: '1.17'
main: org.mossmc.mosscg.MoBoxHunter.Main
authors: [MossCG,Frkovo]
description: A plugin by MossCG for MoBoxMC.
depend:  [MoBoxCore,PlaceholderAPI]
softdepend:
  - RandomEvents
commands:
  moboxhunter:
    description: 主指令
  mbht:
    description: 主指令缩写
permissions:
  moboxhunter.list:
    description: 查看游戏内玩家列表权限
    default: true
  moboxhunter.resetcountdown:
    description: 重置等待时间权限
    default: op
  moboxhunter.reducecountdown:
    description: 减少等待时间权限
    default: op
  moboxhunter.changerole:
    description: 更换游戏角色权限
    default: op
  moboxhunter.changeotherrole:
    description: 更换他人游戏角色权限
    default: op
  moboxhunter.help:
    description: 查看帮助权限
    default: true